
services:
  app:
    build: .
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src:/code/src
      - ./requirements.txt:/code/requirements.txt
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.config
      - .env.secrets
    restart: always
    depends_on:
          ollama:
            condition: service_healthy  # Wait until ollama is healthy
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    env_file:
      - .env.config
    ports:
      - 7869:11434
    volumes:
      - ./scripts:/scripts
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/usr/bin/bash", "/scripts/download_models.sh"] # Download the model
    healthcheck:
      test : ["CMD",/usr/bin/bash,"./scripts/healthcheck.sh"]  # Example health check command
      interval: 60s  # Check every 30 seconds
      timeout: 5s    # Timeout for each check
      retries: 10   # will timeout after 3 retries
      start_period: 300s  # Initial delay before health checks start, will timeout after 15 minutes, increase if the model takes longer to load
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  
